# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1fef668b25065c8b9f88b567bf5332e0e37eb1cc94141bd5e088aac1c982ee93d3bf4ed9076973710bdec5233422826d1e835b51cbe1051f6640f97664897f3

test:
  secret_key_base: 0d6d8eeb3cc3d7e0c924ebe1d7d41a9610d2c37fb23e3067218c8c7beff55f2dd93fe3ca5967f1bf353fabb560720493135cd710b4e780313c2664fef947416d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
